apiVersion: cirrus.ibm.com/v1alpha1
kind: Route
metadata:
  name: zeus-server-preprod-route
spec:
  to:
    kind: Application
    name: zeus-server-preprod
  port:
    targetPort: https
  tls:
    termination: passthrough
  host: zeus-server-preprod.dal.cirrus.ibm.com
