apiVersion: automation.cio/v1alpha1
kind: RepositoryConfig
ealImapNumber: AS000111
build:
  strategy: container-release
  pipeline: python-v3.11-micropipenv-container-image
  version: v2
  config:
    install-packages-app: git-all wget gcc libpq-devel
    install-packages-ci: git-all wget gcc libpq-devel
    cirrus-pipeline-name: my-app-pipeline
    cirrus-project-name: dp-cont
    cirrus-region: wdc-containers
    mcp-enabled: true
release:
  environments:
    - name: test
      deploy-verification-memory-request: q1gb
    - name: pre-production
      deploy-verification-memory-request: q1gb
    - name: production
      deploy-verification-memory-request: q1gb
