apiVersion: cirrus.ibm.com/v1alpha1
kind: Route
metadata:
  name: zeus-server-production-route
spec:
  to:
    kind: Application
    name: zeus-server-production
  port:
    targetPort: https
  tls:
    termination: passthrough
  host: zeus-server-production.dal.cirrus.ibm.com
