apiVersion: cirrus.ibm.com/v1alpha1
kind: Route
metadata:
  name: my-app-pipeline-production-route
spec:
  to:
    kind: Application
    name: my-app-pipeline-production
  port:
    targetPort: https
  tls:
    termination: passthrough
  host: my-app-pipeline-production.dal.cirrus.ibm.com
